"""empty message

Revision ID: d61de9e204d0
Revises: be04cc937f02
Create Date: 2020-02-25 21:53:26.768236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd61de9e204d0'
down_revision = 'be04cc937f02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('edited_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'edited_on')
    # ### end Alembic commands ###
